version: '3.2'
 
services: 
    php:
        container_name: php-code-sample
        build:
            context: ./docker/php/
        restart: always
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www/html
        working_dir: /var/www/html
        command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
        ports:
            - 8001:8000
        depends_on:
          - mysql
        networks:
            - app-network
    mysql:
        container_name: mysql-code-sample
        image: mysql:8
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
             - ./docker/mysql/data:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
        networks:
            - app-network
networks:
  app-network:
    driver: bridge
